# Generated by Django 3.2.9 on 2021-11-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shopping_cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customerId', models.CharField(max_length=100)),
                ('item_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
