# Generated by Django 3.2.9 on 2021-11-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart',
            name='image',
            field=models.CharField(default='default.jpg', max_length=300),
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
